openapi: 3.0.1
info:
  title: ts api
  description: ts api
  version: 1.0.0
servers:
- url: /
paths:
  /raw:
    get:
      tags:
      - RawData
      summary: get RawData
      description: get RawData
      operationId: get_raw_data
      parameters:
      - name: interval
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: start
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
      - name: end
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: get RawData
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RawDataResponse'
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
  /market_break_points:
    get:
      tags:
      - RawData
      summary: get Market Break Points
      description: get Market Break Points
      operationId: get_market_break_point
      responses:
        "200":
          description: get Market Break Points
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketBreakPointResponse'
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
components:
  schemas:
    RawDataResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/RawData'
        query_string:
          type: string
      example:
        data:
        - volume: 2.3021358869347655
          high: 1.4658129805029452
          low: 5.962133916683182
          close: 5.637376656633329
          open: 6.027456183070403
          timestamp: 0
        - volume: 2.3021358869347655
          high: 1.4658129805029452
          low: 5.962133916683182
          close: 5.637376656633329
          open: 6.027456183070403
          timestamp: 0
        query_string: query_string
    RawData:
      type: object
      properties:
        timestamp:
          type: integer
        open:
          type: number
        high:
          type: number
        low:
          type: number
        close:
          type: number
        volume:
          type: number
      example:
        volume: 2.3021358869347655
        high: 1.4658129805029452
        low: 5.962133916683182
        close: 5.637376656633329
        open: 6.027456183070403
        timestamp: 0
    MarketBreakPointResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MarketBreakPoint'
        query_string:
          type: string
      example:
        data:
        - timestamp: timestamp
        - timestamp: timestamp
        query_string: query_string
    MarketBreakPoint:
      type: object
      properties:
        timestamp:
          type: string
      example:
        timestamp: timestamp
x-original-swagger-version: "2.0"

